import { ArrowRight, BookOpen, CalendarDays, ClipboardCheck, FileText, MapPin, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import schoolLogo from "@/assets/school-logo.jpg";
import { homepageCards } from "@/data/site";

export default function Home() {
  return (
    <div>
      <section className="hero-gradient relative overflow-hidden text-secondary-foreground">
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(120deg, transparent 0%, rgba(240,190,70,.32) 48%, transparent 49%)" }} />
        <div className="container relative grid min-h-[680px] gap-14 py-24 md:grid-cols-[1.1fr_0.9fr] md:items-center md:py-32">
          <div>
            <div className="mb-8 flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.2em] text-primary"><span className="h-px w-10 bg-primary" />Official school portal</div>
            <h1 className="max-w-4xl font-display text-5xl font-bold leading-[1.02] md:text-7xl">Education with purpose. <span className="text-primary">Character with direction.</span></h1>
            <p className="mt-8 max-w-2xl text-lg leading-8 text-secondary-foreground/75">Welcome to Shongamiti High School. Explore the school, understand our academic pathways, access official information, and begin an application through a clear and accountable process.</p>
            <div className="mt-10 flex flex-col gap-4 sm:flex-row"><Link to="/admissions/apply" className="btn-gold inline-flex items-center justify-center gap-2">Begin an application <ArrowRight className="h-4 w-4" /></Link><Link to="/school" className="inline-flex items-center justify-center gap-2 rounded-lg border border-secondary-foreground/25 px-6 py-3 font-semibold text-secondary-foreground transition-colors hover:border-primary hover:text-primary">Discover the school</Link></div>
            <div className="mt-12 grid max-w-xl grid-cols-2 gap-6 border-t border-secondary-foreground/15 pt-6 sm:grid-cols-4"><div><p className="font-display text-3xl font-bold text-primary">O–A</p><p className="mt-1 text-xs uppercase tracking-wider text-secondary-foreground/60">Level pathways</p></div><div><p className="font-display text-3xl font-bold text-primary">24/7</p><p className="mt-1 text-xs uppercase tracking-wider text-secondary-foreground/60">Information access</p></div><div><p className="font-display text-3xl font-bold text-primary">1</p><p className="mt-1 text-xs uppercase tracking-wider text-secondary-foreground/60">School community</p></div><div><p className="font-display text-3xl font-bold text-primary">2026</p><p className="mt-1 text-xs uppercase tracking-wider text-secondary-foreground/60">Current portal</p></div></div>
          </div>
          <div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-4 rounded-[2rem] border border-primary/20" /><div className="relative rounded-[1.75rem] border border-primary/25 bg-white/10 p-8 shadow-2xl backdrop-blur"><img src={schoolLogo} alt="Shongamiti High School crest" className="mx-auto h-36 w-36 rounded-full border-4 border-primary/80 object-cover shadow-[var(--shadow-gold)]" /><p className="mt-8 text-center text-xs font-bold uppercase tracking-[0.3em] text-primary">Shongamiti High School</p><p className="mt-4 text-center font-display text-3xl font-bold">Striving for excellence</p><div className="mt-8 grid gap-3 text-sm text-secondary-foreground/75"><div className="flex items-center gap-3 border-t border-secondary-foreground/15 pt-3"><MapPin className="h-4 w-4 text-primary" /> Masvingo Province, Zimbabwe</div><div className="flex items-center gap-3 border-t border-secondary-foreground/15 pt-3"><ShieldCheck className="h-4 w-4 text-primary" /> Formal school information</div></div></div></div>
        </div>
      </section>
      <section className="border-b border-border bg-card"><div className="container grid gap-0 md:grid-cols-3"><Link to="/admissions" className="group flex gap-4 border-b border-border p-6 md:border-b-0 md:border-r"><ClipboardCheck className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><p className="font-bold text-secondary">Admissions pathway</p><p className="mt-1 text-sm leading-6 text-slate-600">Requirements, documents, and online application guidance.</p><span className="mt-3 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-secondary group-hover:text-primary">Explore <ArrowRight className="h-3 w-3" /></span></div></Link><Link to="/academics" className="group flex gap-4 border-b border-border p-6 md:border-b-0 md:border-r"><BookOpen className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><p className="font-bold text-secondary">Academic life</p><p className="mt-1 text-sm leading-6 text-slate-600">Curriculum, pathways, subjects, and examination information.</p><span className="mt-3 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-secondary group-hover:text-primary">Explore <ArrowRight className="h-3 w-3" /></span></div></Link><Link to="/information-centre" className="group flex gap-4 p-6"><FileText className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><p className="font-bold text-secondary">Information centre</p><p className="mt-1 text-sm leading-6 text-slate-600">Official documents, notices, calendars, and policies.</p><span className="mt-3 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-secondary group-hover:text-primary">Explore <ArrowRight className="h-3 w-3" /></span></div></Link></div></section>
      <section className="container py-20 md:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">A deeper school experience</p><h2 className="mt-4 font-display text-4xl font-bold leading-tight text-secondary md:text-5xl">Find the route that matters to you.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The new Shongamiti platform is organised around the questions families, students, staff, and community partners ask most often. Each route connects practical information with the next action.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{homepageCards.map((card) => { const Icon = card.icon; return <Link key={card.title} to={card.href} className="group rounded-2xl border border-border bg-card p-6 shadow-sm transition-all hover:-translate-y-1 hover:shadow-[var(--shadow-elevated)]"><div className="flex items-start justify-between"><span className="rounded-xl bg-primary/15 p-3 text-secondary"><Icon className="h-5 w-5" /></span><ArrowRight className="h-5 w-5 text-slate-400 transition-transform group-hover:translate-x-1 group-hover:text-secondary" /></div><p className="mt-7 text-xs font-bold uppercase tracking-[0.16em] text-primary">{card.eyebrow}</p><h3 className="mt-2 font-display text-2xl font-bold text-secondary">{card.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{card.description}</p></Link>; })}</div></section>
      <section className="bg-muted/60"><div className="container grid gap-10 py-20 md:grid-cols-[1fr_0.8fr] md:items-center md:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Plan your visit</p><h2 className="mt-4 font-display text-4xl font-bold text-secondary">A school built around clear communication.</h2><p className="mt-5 max-w-xl text-base leading-8 text-slate-600">For enquiries about admissions, programmes, school life, or official documents, use the contact routes provided throughout this platform. The admissions office can guide families who need help preparing an application.</p><Link to="/information-centre/announcements" className="mt-7 inline-flex items-center gap-2 font-bold text-secondary hover:text-primary">View current information <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-2xl border border-border bg-card p-7 shadow-sm"><div className="flex items-center gap-3"><CalendarDays className="h-5 w-5 text-primary" /><p className="font-bold text-secondary">Important information</p></div><div className="mt-6 space-y-4 text-sm leading-6 text-slate-600"><p className="border-t border-border pt-4">Application guidance and document requirements are available before you begin.</p><p className="border-t border-border pt-4">Save your application reference number after submission.</p><p className="border-t border-border pt-4">Use the official contact details if you need assistance.</p></div></div></div></section>
    </div>
  );
}
