import { ArrowLeft, ArrowUpRight, CalendarDays, FileText, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { informationItems } from "@/data/site";

const detailCopy: Record<string, { lead: string; sections: Array<{ title: string; body: string }> }> = {
  "admissions-guidance": { lead: "Use this guide to prepare an application record before opening the online admissions form.", sections: [{ title: "Before you begin", body: "Read the entry requirements, identify the requested level, and gather the academic and identity information that will be requested. Families should use the official contact route when a circumstance requires clarification." }, { title: "What the application records", body: "The application captures the student’s requested pathway, previous school, guardian contact details, academic summary, residential address, and supporting document metadata. The submission should be reviewed carefully before it is sent." }, { title: "After submission", body: "The portal issues a reference number. Retain it securely and use it with the applicant email when contacting the admissions office or checking the progress of the application." }] },
  "term-dates": { lead: "This publication area is reserved for the approved school calendar and dated term notices.", sections: [{ title: "A clear academic calendar", body: "The final calendar should show term opening and closing dates, public holidays, examination periods, consultation dates, and important school events in a form families can print or save." }, { title: "Keeping dates current", body: "When a date changes, the school office should publish a revised version with the new publication date and a short explanation. Older versions should remain archived rather than silently overwritten." }] },
  "parent-circulars": { lead: "Circulars provide a formal route for school offices to communicate actions, deadlines, and decisions to families.", sections: [{ title: "What a circular should include", body: "Each circular should have a clear title, issue date, responsible office, audience, required action, and contact route. The writing should be direct enough for a family to understand what happens next." }, { title: "Acknowledgement and record", body: "Where a response is required, the final publication can link to the relevant form or portal. The information centre should retain an accessible archive for reference." }] },
  "student-conduct": { lead: "The conduct and appearance publication will explain the shared standards that support a safe and purposeful learning environment.", sections: [{ title: "A consistent standard", body: "School expectations should be written in positive, specific language and applied consistently across classrooms, activities, travel, and school events." }, { title: "Fair process", body: "A complete policy should explain how concerns are raised, how students are heard, how families are contacted, and how restorative or disciplinary steps are recorded." }] },
  "academic-departments": { lead: "This guide will connect families and students with the subjects, departments, and academic support structures available at the school.", sections: [{ title: "Academic organisation", body: "Department information should identify the subjects offered, the relevant level, the type of learning involved, and the staff or office responsible for current guidance." }, { title: "Choosing a pathway", body: "Students should consider their interests, present attainment, study habits, and future goals. The school will provide formal subject-combination guidance through the academic office." }] },
  "history-milestones": { lead: "The heritage record will grow as approved school milestones, archival sources, and community accounts are prepared for publication.", sections: [{ title: "Institutional memory", body: "A school history is strongest when it recognises the learners, educators, families, and community partners whose work has shaped the institution over time." }, { title: "A living record", body: "Future additions may include a dated chronology, leadership records, photographs, achievements, and alumni contributions, each identified with its source and publication context." }] },
};

export default function InformationDocument() {
  const { slug } = useParams();
  const item = informationItems.find((entry) => entry.slug === slug);
  const copy = item ? detailCopy[item.slug] : null;
  if (!item || !copy) return <section className="container max-w-2xl py-24 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Information centre</p><h1 className="mt-4 font-display text-4xl font-bold text-secondary">Publication not found.</h1><Link to="/information-centre/documents" className="btn-gold mt-8 inline-flex">Return to document library</Link></section>;
  const Icon = item.icon;
  return <section className="container max-w-5xl py-14 md:py-20"><Link to="/information-centre/documents" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-secondary"><ArrowLeft className="h-4 w-4" /> Document library</Link><div className="mt-9 grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><aside className="h-fit rounded-2xl border border-border bg-muted/60 p-6 lg:sticky lg:top-28"><span className="inline-flex rounded-xl bg-primary/15 p-3 text-secondary"><Icon className="h-6 w-6" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[0.18em] text-primary">{item.type}</p><h1 className="mt-3 font-display text-3xl font-bold leading-tight text-secondary">{item.title}</h1><p className="mt-5 text-sm leading-7 text-slate-600">{item.summary}</p><div className="mt-7 border-t border-border pt-5 text-xs leading-6 text-slate-500"><p className="font-bold uppercase tracking-wider text-secondary">Publication record</p><p className="mt-2">{item.date}</p><p>Responsible office: School administration</p></div><Link to="/information-centre" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-secondary hover:text-primary">Information centre overview <ArrowUpRight className="h-4 w-4" /></Link></aside><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Official publication</p><p className="mt-4 max-w-3xl font-display text-3xl font-bold leading-tight text-secondary md:text-4xl">{copy.lead}</p><div className="mt-10 space-y-9">{copy.sections.map((section) => <article key={section.title} className="border-b border-border pb-9"><h2 className="font-display text-2xl font-bold text-secondary">{section.title}</h2><p className="mt-4 text-base leading-8 text-slate-600">{section.body}</p></article>)}</div><div className="mt-9 flex gap-3 rounded-xl bg-primary/10 p-4 text-sm leading-6 text-secondary"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" />Official documents should be read together with the latest school notices and any instructions from the responsible office.</div></div></div><div className="mt-16 border-t border-border pt-8"><div className="flex items-start gap-3 text-sm leading-6 text-slate-600"><CalendarDays className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p><strong className="text-secondary">Need another record?</strong> Return to the library to browse calendars, circulars, policies, academic guides, and heritage publications.</p><Link to="/information-centre/documents" className="ml-auto hidden shrink-0 items-center gap-2 font-bold text-secondary hover:text-primary sm:inline-flex">Browse library <FileText className="h-4 w-4" /></Link></div></div></section>;
}
