import { BrowserRouter, Route, Routes } from "react-router-dom";
import { SiteShell } from "@/components/SiteShell";
import Home from "@/pages/Home";
import Application from "@/pages/Application";
import ApplicationStatus from "@/pages/ApplicationStatus";
import StaffPortal from "@/pages/StaffPortal";
import InformationLibrary from "@/pages/InformationLibrary";
import { AboutDirectory, AcademicDirectory, AcademicsPage, AdmissionsDirectory, AdmissionsPage, InformationCentrePage, SchoolPage, StudentLifePage, TopicPage } from "@/pages/PortalSections";

export default function App() {
  return <BrowserRouter><SiteShell><Routes><Route path="/" element={<Home />} /><Route path="/school" element={<AboutDirectory />} /><Route path="/school/overview" element={<SchoolPage />} /><Route path="/school/leadership" element={<TopicPage topic="leadership" />} /><Route path="/school/staff" element={<TopicPage topic="staff" />} /><Route path="/school/history" element={<TopicPage topic="history" />} /><Route path="/academics" element={<AcademicDirectory />} /><Route path="/academics/overview" element={<AcademicsPage />} /><Route path="/academics/curriculum" element={<TopicPage topic="curriculum" />} /><Route path="/academics/o-level" element={<TopicPage topic="curriculum" />} /><Route path="/academics/a-level" element={<TopicPage topic="combinations" />} /><Route path="/academics/subject-combinations" element={<TopicPage topic="combinations" />} /><Route path="/academics/results" element={<TopicPage topic="results" />} /><Route path="/admissions" element={<AdmissionsDirectory />} /><Route path="/admissions/overview" element={<AdmissionsPage />} /><Route path="/admissions/requirements" element={<TopicPage topic="requirements" />} /><Route path="/admissions/fees" element={<TopicPage topic="requirements" />} /><Route path="/admissions/documents" element={<TopicPage topic="documents" />} /><Route path="/admissions/apply" element={<Application />} /><Route path="/admissions/status" element={<ApplicationStatus />} /><Route path="/student-life" element={<StudentLifePage />} /><Route path="/student-life/sports" element={<TopicPage topic="sports" />} /><Route path="/student-life/houses" element={<TopicPage topic="student-leadership" />} /><Route path="/student-life/clubs" element={<TopicPage topic="student-leadership" />} /><Route path="/student-life/guidance" element={<TopicPage topic="guidance" />} /><Route path="/student-life/leadership" element={<TopicPage topic="student-leadership" />} /><Route path="/information-centre" element={<InformationCentrePage />} /><Route path="/information-centre/announcements" element={<TopicPage topic="announcements" />} /><Route path="/information-centre/documents" element={<InformationLibrary />} /><Route path="/information-centre/circulars" element={<TopicPage topic="announcements" />} /><Route path="/information-centre/policies" element={<TopicPage topic="policies" />} /><Route path="/staff" element={<StaffPortal />} /><Route path="*" element={<NotFound />} /></Routes></SiteShell></BrowserRouter>;
}

function NotFound() { return <section className="container max-w-2xl py-24 text-center"><p className="text-xs font-bold uppercase tracking-[0.22em] text-primary">404 · Page not found</p><h1 className="mt-4 font-display text-5xl font-bold text-secondary">This route is not in the school directory.</h1><p className="mt-5 text-base leading-8 text-slate-600">Return to the school portal and choose a section from the formal navigation.</p><a href="/" className="btn-gold mt-8 inline-flex">Return to home</a></section>; }
